# Generated by Django 4.2.4 on 2023-10-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_rate_avg_article_rate_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlerating',
            name='rating',
            field=models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
