version: '3.9'

services:


  pgadmin:
    container_name: pgadmin_bitpin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    ports:
      - "5050:5050"
    depends_on:
      - postgres

  redis:
    container_name: redis_bitpin
    image: redis:latest

  backend:
    container_name: backend_bitpin
    build:
      context: .
      dockerfile: Docker/DockerfileBackend
      args:
        ENV_FILE: .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: postgres_bitpin
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data


volumes:
  pg_data:
