# Generated by Django 4.2.4 on 2023-08-03 10:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mobile_number', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^989[0-3,9]\\d{8}$', 'Enter a valid mobile number')], verbose_name='mobile number')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='location')),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last seen')),
                ('is_banned', models.BooleanField(default=False, verbose_name='banned')),
                ('is_vip', models.BooleanField(default=False, verbose_name='vip')),
                ('is_kyc_l1_done', models.BooleanField(default=False, verbose_name='KYC 1')),
                ('is_kyc_l2_done', models.BooleanField(default=False, verbose_name='KYC 2')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
