# Generated by Django 4.2.4 on 2023-08-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_userprofile_irr_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(blank=True, default='generate_random_referral', max_length=50, unique=True),
        ),
    ]
