# Generated by Django 4.2.4 on 2023-08-28 06:59

from django.db import migrations, models
import user_accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0003_userprofile_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(default=user_accounts.models.generate_random_referral, max_length=50, unique=True),
        ),
    ]
